[build.targets.sdist]
exclude = [
    "/.github",
    "/docs",
    "/tests",
]

[envs.default]
installer = "uv"

[envs.hatch-test]
installer = "uv"
[[envs.hatch-test.matrix]]
python = ["3.12", "3.11", "3.10"]
backend = ["torch", "tensorflow"]
[envs.hatch-test.overrides]
matrix.backend.env-vars = "KERAS_BACKEND"
matrix.backend.extra-dependencies = [
    {value="torch", if = ["torch"]},
    {value="tensorflow", if = ["tensorflow"]}
]

[envs.dev]
installer = "uv"
extra-dependencies = ["torch", "ruff", "pre-commit"]
[envs.dev.env-vars]
KERAS_BACKEND="torch"

[envs.docs]
dependencies = [
    "mkdocs",
    "mkdocs-minify-plugin",
    "mkdocstrings-python",
    "pygments"
]
[envs.docs.env-vars]
SOURCE_DATE_EPOCH = "1580601600"
PYTHONUNBUFFERED = "1"
MKDOCS_CONFIG = "mkdocs.yml"
[envs.docs.scripts]
build = "mkdocs build --config-file {env:MKDOCS_CONFIG} --clean --strict {args}"
serve = "mkdocs serve --config-file {env:MKDOCS_CONFIG} --dev-addr localhost:8000 {args}"

[envs.types]
installer = "uv"
extra-dependencies = ["mypy>=1.0.0"]
[envs.types.scripts]
check = "mypy --install-types --non-interactive {args:tests}"

[build.targets.wheel]
packages = ["src/softadapt"]

[envs.hatch-static-analysis]
config-path = "ruff.toml"
dependencies = ["ruff==0.11.7"]