[project]
name = "softadapt_keras"
version = "0.0.2"
authors = [
  { name="A. Ali Heydari", email="aliheydari@ucdavis.edu"},
  { name="Jacob Logas", email="logasja@gatech.edu" },
]
description = "SoftAdapt: Techniques for Adaptive Loss Weighting of Neural Networks with Multi-Part Loss Functions implemented in Keras"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: MIT Software License",
    "Programming Language :: Python :: 3.10",
    "Topic :: Scientific/Engineering :: Artificial Intelligence"
]
keywords=["Physics-Informed Neural Networks", "Balancing PINNs Loss",
                "Adaptive-Weighting, Multi-Task-Nerual-Networks Optimization",
                "Gradient-Descent-Weighting, Machine Learning"]
dependencies = ["findiff", "keras>=3.0.0"]

[project.urls]
Homepage = "https://github.com/dr-aheydari/SoftAdapt-Keras"
Issues = "https://github.com/dr-aheydari/SoftAdapt-Keras/issues"