# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Push Validation

on: push

jobs:
  validate:
    name: Validate Changes
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false
    - name: Install Hatch
      uses: pypa/hatch@install
    - name: Format Check
      run: hatch fmt --check
    - name: Run Tests
      run: hatch test --all