# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Test

on:
  push:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

env:
  PYTHONUNBUFFERED: "1"
  FORCE_COLOR: "1"

jobs:
  run: 
    name: Hatch on ${{ startsWith(matrix.os, 'macos-') && 'macOS' || startsWith(matrix.os, 'windows-') && 'Windows' || 'Linux' }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        # os: [ubuntu-latest, windows-latest, macos-latest]
        os: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v4

    - name: Install Hatch
      uses: pypa/hatch@install

    - name: Run static analysis
      run: hatch fmt --check

    # - name: Check types
    #   run: hatch run types:check

    - name: Run tests
      run: hatch test -a --cover-quiet --randomize --parallel --retries 5 --retry-delay 3

    - name: Disambiguate coverage filename
      run: mv .coverage ".coverage.${{ matrix.os }}"

    - name: Upload coverage data
      uses: actions/upload-artifact@v4
      with:
        include-hidden-files: true
        name: coverage-${{ matrix.os }}
        path: .coverage*
  coverage:
    name: Report Coverage
    runs-on: ubuntu-latest
    needs:
    - run
    steps:
    - uses: actions/checkout@v4

    - name: Install Hatch
      uses: pypa/hatch@install

    - name: Trigger build for auto-generated files
      run: hatch build --hooks-only

    - name: Download coverage data
      uses: actions/download-artifact@v4
      with:
        pattern: coverage-*
        merge-multiple: true

    - name: Combine coverage data
      run: hatch run coverage:combine

    - name: Export coverage reports
      run: |
        hatch run coverage:report-xml
        hatch run coverage:report-uncovered-html
        hatch run coverage:report-md

    - name: Upload uncovered HTML report
      uses: actions/upload-artifact@v4
      with:
        name: uncovered-html-report
        path: htmlcov

    - name: Generate coverage summary
      run: hatch run coverage:generate-summary

    - name: Write coverage summary report
      run: hatch run coverage:write-summary-report

    - name: Update coverage summary comment
      id: md
      uses: mediatech15/markdown-to-summary-action@v1.1
      with:
        file: 'coverage-report.md'
        check_name: md
        conclusion: success

    - name: Update coverage summary comment
      id: md2
      uses: mediatech15/markdown-to-summary-action@v1.1
      with:
        file: 'coverage.md'
        check_name: md
        conclusion: success

  # https://github.com/marketplace/actions/alls-green#why
  check: # This job does nothing and is only used for the branch protection
    name: Check tests successful
    if: always()

    needs:
    - coverage

    runs-on: ubuntu-latest

    steps:
    - name: Decide whether the needed jobs succeeded or failed
      uses: re-actors/alls-green@release/v1
      with:
        jobs: ${{ toJSON(needs) }}